### PR TITLE
Add initializing on Appdelegate

### PR DESCRIPTION
**Pull request by zhigang1992**

### CODE REVIEW

**Comment by Watson1978** [comment]
I think this request is unnecessary if you would use https://github.com/Pixate/RubyMotion-PixateFreestyle/commit/7cefa59dff1fa795800e6ec7b7a2f4896ebd15d6 commit.

**Comment by zhigang1992** [comment]
Is this commit on master branch?

—

**Comment by Watson1978** [comment]
Yes

**Comment by zhigang1992** [comment]
Can you check that if gem download here is correct,
http://rubygems.org/gems/motion-pixatefreestyle
The code doesn't match what's on the master, can you update it?

the `pixatefreestyle_code.rb` put the initialize in the `def style`.

**Comment by Watson1978** [comment]
Sorry, I don't own this project in rubygem.org, so I can't push/update to rubygem.org.

**Pull request closed without merging**
