### PR TITLE
Update the gem for Pixate 2.1

### PR DESCRIPTION
**Pull request by killion**
The only change is the framework is now called PixateFreestyle. I left references to Pixate as "Pixate" on the rubymotion side of things to make things simpler for people upgrading.

### CODE REVIEW

**Comment by pcolton** [comment]
The Pixate object is used in a few other places, look at the pixate.rb file. For example:

```
 Pixate.applyStylesheets 
```

Also, this method is now gone since licenses aren't required any more:

```
  license = "Pixate.licenseKey('#{@key}', forUser:'#{@user}')\n"
```

Instead this line should now be called:

```
  PixateFreestyle.initializePixateFreestyle()
```

**Comment by Watson1978** [comment]
I think better if you show the user and key are deprecated, like

``` diff
diff --git a/lib/motion/project/pixate.rb b/lib/motion/project/pixate.rb
index 0441c05..94f5d07 100644
--- a/lib/motion/project/pixate.rb
+++ b/lib/motion/project/pixate.rb
@@ -18,8 +18,24 @@ def framework=(path)
     end
   end

+  def user=(user)
+    display_deprecated_message
+  end
+
+  def key=(key)
+    display_deprecated_message
+  end
+
   private

+  def display_deprecated_message
+    unless @displayed_deprecated_message
+      App.warn "The user and key are deprecated in motion-pixate gem and will be removed in an upcoming release."
+      App.warn "Please update to latest PixateFreestyle.framework"
+    end
+    @displayed_deprecated_message = true
+  end
+
   def create_code
     license = ""
     if @user && @key
```

**Comment by Watson1978** [comment]
Never mind for above my comment.
Because looks like this patch just support for newest framework only. (PixateFreestyle binary file that there is newest framework only)

```
@config.vendor_project(path, :static, :products => ['PixateFreestyle'], :headers_dir => 'Headers')
```

So, you would need to remove code for license

``` diff
diff --git a/lib/motion/project/pixate.rb b/lib/motion/project/pixate.rb
index 0441c05..a223130 100644
--- a/lib/motion/project/pixate.rb
+++ b/lib/motion/project/pixate.rb
@@ -21,15 +21,9 @@ def framework=(path)
   private

   def create_code
-    license = ""
-    if @user && @key
-      license = "PixateFreestyle.licenseKey('#{@key}', forUser:'#{@user}')\n"
-    end
-
     code = <<EOF
 # This file is automatically generated. Do not edit.

-#{license}
 def style(str)
   PixateFreestyle.styleSheetFromSource(str, withOrigin:0)
   PixateFreestyle.applyStylesheets
```

**Comment by Watson1978** [comment]
Also, you can remove user and key from README.md

`````` diff
diff --git a/README.md b/README.md
index 253e043..5372a0c 100644
--- a/README.md
+++ b/README.md
@@ -28,8 +28,6 @@ This **free** key is available at [http://pixate.com/key](http://pixate.com/key)
 ```ruby
 Motion::Project::App.setup do |app|
   # ...
-  app.pixate.user = 'USER ID' # Valid key removes "splash screen"
-  app.pixate.key  = 'KEY CODE' # Visit pixate.com/key for a free key
   app.pixate.framework = 'vendor/PixateFreestyle.framework'
 end
``````

```
```

**Comment by killion** [comment]
Thanks @Watson1978 and @pcolton! I updated the pull request, please let me know if I missed anything else.

**Comment by killion** [comment]
Thanks! Is 2.1 pushed to rubygems?

**Comment by pcolton** [comment]
Yes, but because there were so many changes, I've pushed a new gem, called motion-pixatefreestyle. See https://rubygems.org/gems/motion-pixatefreestyle

**Pull request merged**
