### PR TITLE
Add support for .sass extension.

### PR DESCRIPTION
**Pull request by mackato**
Hi, I would like to use SASS style syntax. Please add support for .sass extension.

### CODE REVIEW

**Comment by Watson1978** [comment]
I think that you should use `"sass/default.s[ac]ss"` instead of `"sass/default.s*ss"`.
Because `"sass/default.s*ss"` will match with `default.sxxxxss` etc :)

**Comment by mackato** [comment]
OK, I'll fix it.

**Comment by Watson1978** [comment]
Thanks !!

**Comment by mackato** [comment]
My pleasure.

**Pull request merged**
