### PR TITLE
Forgot to put the PixateFreestyle.initializePixateFreestyle in the README.md

### PR DESCRIPTION
**Pull request by mmolhoek**
Thought it would be handy to put that in the README.md as well, otherwise following the code in the README does not work.

### CODE REVIEW

**Comment by Watson1978** [comment]
PixateFreestyle engin will be initialized automatically at boot time with 7cefa59dff1fa795800e6ec7b7a2f4896ebd15d6
Thank you.

**Comment by mmolhoek** [comment]
Hi Watson, sorry to bother you, but could you tell me how i could use the release where this is fixed? Do I need to compile the Framework myself somehow? If i download the zip of the latest development branch, it does not contain the Framework, just the sources...sorry, maybe this is a beginners question, i am a bit of a newbee when it comes to FrameWork building :)
Greetings, Mischa

**Comment by Watson1978** [comment]
You can use my patch by adding the below configuration into Gemfile.

```
gem 'motion-pixatefreestyle', :git => "https://github.com/Pixate/RubyMotion-PixateFreestyle.git"
```

Then run following command,

```
$ bundle install
```

(You should install the Bundler gem with `gem install bundler`  in advance)

(I can't bump of new version because I don’t own this gem in RubyGems.org)

**Comment by mmolhoek** [comment]
ok, thank you for your quick response!,
i  installed your version now, (Using motion-pixatefreestyle 2.1 from https://github.com/Pixate/RubyMotion-PixateFreestyle.git (at master)),
but i still need to put the PixateFreestyle.initializePixateFreestyle in 
def application(application, didFinishLaunchingWithOptions:launchOptions),
 otherwise my default.css is not used. 
i installed PixateFreestyle (2.1.4) within the Motion::Project::App.setup block, which installed just fine with rake pod:install,
any idea what i might be doing wrong?
tanx, Mischa

**Comment by Watson1978** [comment]
You will need to run `bundle exec rake XXXX` in order to use the gem which was installed with `bundle install`

**Comment by mmolhoek** [comment]
doing that but still does not work unless i explicitly set PixateFreestyle.initializePixateFreestyle,

also, after putting

``` ruby
PixateFreestyle.styleSheetFromFilePath('/Users/mischa/Projects/rubymotion/calendar/resources/default.css', withOrigin:0)
PixateFreestyle.updateStylesForAllViews
PixateFreestyle.currentApplicationStylesheet.monitorChanges = true
```

in def application(application, didFinishLaunchingWithOptions:launchOptions),
i can still not live update the css file and see it change iin the simulator...

**Comment by mmolhoek** [comment]
while when i stop the simulator and rerun rake, the changes to the css are visable...

**Comment by mmolhoek** [comment]
screen shot 2014-08-24 at 14 28 40
screen shot 2014-08-24 at 14 30 34

the menubar should become green, but stays grey

**Comment by mmolhoek** [comment]
pictures say more than a thousand words :) ps, you don't see the default.css file , but is is there and the tab-bar { background-color: green; } is set

**Comment by Watson1978** [comment]
When run app, resouce files are copied into app bundle.
You should change the bundled file for live updating.

You can know bundled path with `NSBundle.mainBundle.bundlePath`

**Comment by mmolhoek** [comment]
aaahh, great, will give that i try for the live updating issue :)
any ideas on the PixateFreestyle.initializePixateFreestyle issue, although i can live with that isseu if live update is working :), hold on , testing now

**Comment by Watson1978** [comment]
I prefer https://github.com/Watson1978/motion-pixate-observer for live updating :p
It will support iOS device too if device was connected on same Wifi network with your develop machine.

**Comment by mmolhoek** [comment]
ok, i will try that then, as i don't get this working :), will let you know when i get it working thought :)
does https://github.com/Watson1978/motion-pixate-observer  also work on the simulator, because thats where i am running the app at the moment, or does it need a real device?

**Comment by mmolhoek** [comment]
screen shot 2014-08-24 at 15 00 23

it seems to sent stuff when i change the css, but on the simulator, nothing changes

**Comment by mmolhoek** [comment]
you can also see in the REPL it receives the css:

screen shot 2014-08-24 at 15 10 52

**Comment by Watson1978** [comment]
If it does not work, PixateFreestyle.framework have changed some things and I don't know it (I never contribute PixateFreestyle.framework). Could you check the changing at https://github.com/Pixate/pixate-freestyle-ios ?

At least, motion-pixate-observer works well as exepect with PixateFreestyle.framework v2.1.0 (https://github.com/Pixate/pixate-freestyle-ios/releases)

**Comment by mmolhoek** [comment]
ok, i will try the v2.1.0 then :), hold on

**Comment by mmolhoek** [comment]
indeed, now it works :) :+1: with your server, although it takes about 10 to 60 seconds before it changes, is that normal behaviour?

**Comment by mmolhoek** [comment]
so, something got messed up in version 2.1.4, which is the current stable...

**Comment by Watson1978** [comment]
Maybe, I think the codes for monitoring using PixateFreestyle only will work with v2.1.0.

```
PixateFreestyle.styleSheetFromFilePath('/Users/mischa/Projects/rubymotion/calendar/resources/default.css', withOrigin:0)
PixateFreestyle.updateStylesForAllViews
PixateFreestyle.currentApplicationStylesheet.monitorChanges = true
```

If work with v2.1.0 on your environment, you can report this problem to https://github.com/Pixate/pixate-freestyle-ios

**Comment by mmolhoek** [comment]
indeed, changing back to 2.1.4, and it does not work anymore. it works in 2.1, it does not anymore in 2.1.1 and up

**Pull request closed without merging**
